# Generated by Django 4.1.7 on 2023-03-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('articul', models.CharField(blank=True, max_length=256, null=True, verbose_name='Артикул в магазине')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст Описания')),
                ('photo_urls', models.TextField(blank=True, null=True, verbose_name='Список ссылок фотографий')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phars_app.category', verbose_name='Категория товара')),
            ],
        ),
    ]
